- svmbir/svmbir.py
The sigma_y scaling of the weights was being applied in python, and the SigmaY value for the c-code was set to 1.  I moved the sigma_y scaling to the c-code so the terminal output summary reflects the correct SigmaY setting.
A verbose setting argument was recently added to the c-code so I added 'verbose' arguments to the project() and recon() functions.
> Pull request from Jordan

- demo/demo_simple.py
- svmbir/phantom.py
I tried to generate a 3D Shepp-Logan phantom based on the reference papers. I wrote 2 functions: one generates ellipsoid and the other one generates the 3D Shepp-Logan phantom defined in the reference papers.
[1]  Kak AC, Slaney M. Principles of computerized tomographic imaging. Page.102. IEEE Press, New York, 1988.
https://engineering.purdue.edu/~malcolm/pct/CTI_Ch03.pdf
[2] Koay, Cheng Guan; Sarlls, Joelle E.; Özarslan, Evren (2007). "Three-Dimensional Analytical Magnetic Resonance Imaging Phantom in the Fourier Domain". Magnetic Resonance in Medicine. 58. pp. 430–436. on 2013-02-16.
https://web.archive.org/web/20130216192913/http://stbb.nichd.nih.gov/pdf/koayMRM07.pdf
> Added 3D Shepp-Logan phantom generator.

- svmbir/_utils.py
- svmbir/svmbir.py
I changed the dtype of the output array for recon() and project() to float32 to match the precision of the c-code. Mainly to avoid excessive memory usage for large images.
Also free up the "weights" array in recon() (if computed internally) before calling the execuable.
> Output dtype now float32 for recon(),project()

- setup.py
The sv-mbirct submodule got reverted to an old commit.
Developers should run 
```
git submodule sync
git submodule update
```
on your local repository especially if you're seeing conflicts with the submodule.  It was changed a couple weeks ago to point to a different fork, so you may see strange effects unless you run the above commands, or re-clone.
> Update submodule commit

- environment.yml
- requirements.txt
The conda environment created by the recent update of environment.yml (that moves everything to pip requirements) breaks the cython interface in linux.  The cython interface seems to install OK, but at runtime I get "undefined symbols" errors in the .so file.  This happens both when I build with CC=gcc and CC=icc.  It only happens for me in linux--mac/clang and mac/icc don't give me a problem.
When I create an environment with the older environment.yml the problem goes away.  The package list created in the older environment is quite a bit longer and it's not obvious to me which is the critical piece that's missing (or the wrong version). 
Until this is tracked down, this branch fixes the issue.
> Fix broken environment.yml for linux

- svmbir/interface_py_c.py
Update of the C-code. Got a roughly 6x speedup in calculating the A matrix. 
Also includes a bug fix where an index can overflow for large recon volumes.
> parallelization of system matrix calculation

- svmbir/_utils.py
- svmbir/interface_cy_c.pyx
- svmbir/interface_py_c.py
- svmbir/svmbir.py
The structure of the mult-resolution recursion made it impossible to de-allocate the initial condition arrays before running the reconstruction.  I pushed the recursion from recon() into the cython/cmdline interface functions. 
- Now svmbir.recon() calls ci.multires_recon(), instead of calling ci.fixed_resolution_recon(). 
- Now the initial condition from the lower resolution is de-allocated before starting the current resolution recon. 
-  I made this change for both cython and command line interface functions. 
- Also reordered the recon() argument order to group them more logically, IMO
The changes passed the unit tests.
Memory usage for a TEM problem reduced from 80G to 30G.
> Update multires-recon recursion

- svmbir/svmbir.py
Default value of the sharpness parameter was incorrectly set to 1.0 instead of 0.0 as is in the specification.
It is now set to the correct value of 0.0
> Fix incorrect default value of sharpness parameter 

- svmbir/svmbir.py
Fixes the documentation issue with the unwanted expansion of the default cache path.  Also changes the default cache path to '\~/.cache/svmbir' from '\~/.cache/svmbir/parbeam'.
> svmbir_lib_path

- demo/demo_2D_microscopy.py
- demo/demo_2D_shepp_logan.py
- demo/demo_3D_microscopy.py
- demo/demo_3D_shepp_logan.py
- demo/demo_multires_comparison.py
- demo/demo_prox.py
- svmbir/svmbir.py
Argument order of `svmbir.project()` is changed from
`svmbir.project(angles,image,...)` to
`svmbir.project(image,angles,...)`.
This makes the function more consistent with the `recon` and new `backproject` functions.
A check is also added for the `project()` input arguments' shape so that if the original order is used, a warning is printed, the array id's are swapped, and the function proceeds. So any existing user code that uses the `project()` function won't break.
All the demos that use the function are also changed accordingly.
> Changed project() argument order to (image,angles,...)

- svmbir/_utils.py
- svmbir/svmbir.py
This is to check for negative weights and to fix a case when the automatic weights could be negative. 
In addition, I think I found a bug in a test where an ``or`` should have been an ``and``. 
See if you agree.
> Make fixes for issue #213: negative weights

- svmbir/interface_cy_c.pyx
- svmbir/interface_py_c.py
- svmbir/phantom.py
- svmbir/svmbir.py
- tests/test_recon.py
The main purpose of this PR is to address a warning resulting from the missing "r" preceding this docstring
https://github.com/cabouman/svmbir/blob/83e72b1fdf91d8193418166a4d2b10f70ed6437c/svmbir/svmbir.py#L34, which is required due to the presence of `\pi` in the docstring.
Other minor changes:
- Switch first line summaries to imperative mood as recommended by PEP8.
- Add missing terminating periods for consistency.
- Whitespace cleanup.
Some issues not addressed (yet -- feel free to add changes to the branch for this PR):
- Incomplete copyright statements "Copyright (C) by" in file headers.
- The absence of a line-length limit reduces readability.
> Minor docstring changes

- MANIFEST.in
- dev_scripts/build_dist.sh
- pyproject.toml
- requirements.txt
- setup.py
Updates to requirements. 
In particular `numpy>=1.22` was added to pyproject.toml, setup.py, and requirements.txt
in order to solve issue #224 error caused when there's a mismatch in numpy version between building and running the package.
Note this error could re-appear in future numpy versions.
> Fix for numpy version mismatch

- demo/demo_2D_microscopy.py
- demo/demo_2D_shepp_logan.py
- demo/demo_3D_microscopy.py
- demo/demo_3D_shepp_logan.py
- demo/demo_fanbeam.py
- demo/demo_multires_comparison.py
- demo/demo_prox.py
I updated the parameter values for the demos so that:
- They are all the same
- They yield consistent image quality
- They all use 2 levels of multi-resolution (except the prox demo)
> Update demos to use consistent parameter settings

- demo/demo_fanbeam.py
- svmbir/interface_cy_c.pyx
- svmbir/svmbir.py
New geometry 'fan-flat' added to recon(), project(), and backproject() operators.
This changes valid geometries from ['parallel', 'fan'] to ['parallel', 'fan-curved', 'fan-flat']
Specifying 'fan' geometry will now raise an exception.
> Added support for flat array fan-beam geometry

- demo/demo_3D_microscopy.py
- demo/demo_3D_shepp_logan.py
- demo/demo_fanbeam.py
- demo/demo_multires_comparison.py
- demo/demo_prox.py
- svmbir/_utils.py
- svmbir/svmbir.py
This PR modifies the default `snr_db` from 30.0 to 40.0, and `magnification` from None to 1.0 in functions `recon()`, `project()`, and `backproject()`. Also, the checker for `magnification=None` is removed in these functions.
For the corner case where `magnification` of fan beam reconstruction mismatches the real magnification, we should simply get a reconstruction with a scaled intensity.
Tested this corner case with the fanbeam demo script. Passed in the default `magnification=1.0` for `recon()` function. The reconstruction looks identical as before, except that the display window changes from 1.0-1.2 to 0.5-0.6.
> modified default values for snr_db and magnification

- svmbir/svmbir.py
Changed the Exception generated for 'geometry'='fan' to the FutureWarning:
'fan' geometry will be removed in a future release. Fan beam geometry is now specified as either 'fan-curved' or 'fan-flat'. Defaulting to 'fan-curved'.
> Add FutureWarning for deprecation of 'fan' geometry specifier.

- dev_scripts/build_dist.sh
- dev_scripts/manylinux.sh
- dev_scripts/test_pypi.sh
Most importantly, this pulls in a critical fix to the C code related to va_arg usage in multialloc().  On macOS 12.2 (M1) it was observed to produce garbage values for the array size passed to multialloc due to a type mismatch in the va_arg arguments.
> Bug fix related to va_arg usage in multialloc

- docs/requirements.txt
Readthedocs build is failing because of the numpy dependency.  They're building with python 3.7, which numpy==1.22 doesn't support.
Removing the numpy version requirement in docs/requirements.txt should fix this.
> Remove numpy version from docs/requirements.txt

- .readthedocs.yaml
Trying to fix the readthedocs build.  It's currently failing because the default build uses python 3.7.  Adding a configuration file to specify the python version.
> Add .readthedocs.yaml to specify python version

- docs/.gitattributes
- docs/source/figs/geom-fan-curved.png
- docs/source/figs/geom-fan-flat.png
- docs/source/figs/geom-fan.png
- docs/source/figs/geom-parallel.png
- docs/source/overview.rst
This is an update of the documentation to better describe the different fan geometries now supported.
I added better quality png images, and added a git-lfs filter so the image files should be hosted on Git LFS and not in the repo itself.  First time trying this, so need to check the auto readthedocs build after this is merged into master.
> Update documentation of fan geometries; add figures and git-lfs filter

- dev_scripts/test_pypi.sh
- requirements.txt
- setup.py
A couple fixes to the installers.
Also Pillow 9.4 is causing svmbir import to fail on MacOS/x86_64, so restricting to Pillow<=9.3.
No need to bump svmbir version.
> update installer, requirements

- dev_scripts/test_pypi.sh
- docs/.gitattributes
- setup.py
- svmbir/__init__.py
Had to make a fix in setup.py for the conda-forge build. This requires new source distribution, so new version.
- Update requirements with Pillow<=9.3 (9.4 is causing import fail on MacOS/x86_64)
- Update setup.py for MacOS builds
> merge for release 0.3.3

- svmbir/_utils.py
- svmbir/svmbir.py
- Turn off multi-resolution by default when using proximal map
- Check `prox_image` input for valid shape
> Proximal map fixes

- docs/requirements.txt
- docs/source/conf.py
This is a fix to the sphinx docs.
Charlie previously had the following error:
```
Extension error:
You must configure the bibtex_bibfiles setting
```
This is because the bib file was not specified in `docs/source/conf.py`
The readthedocs should build without issues now.
> Sphinx hotfix
